<!DOCTYPE HTML>
<!DOCTYPE html PUBLIC "" "">
<html lang="en-US" prefix="og: http://ogp.me/ns#">
<head>
    <meta content="IE=11.0000" http-equiv="X-UA-Compatible">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://gmpg.org/xfn/11" rel="profile">
    <link href="http://freeiphone7plusgiveaway.win/xmlrpc.php" rel="pingback">
    <title>Win a Free iPhone 7 Plus Giveaway &amp; iPhone News</title>
    <!-- Open Graph Meta Tags generated by MashShare 3.3.7 - https://mashshare.net -->
    <meta content="article" property="og:type">
    <meta content="Win a Free iPhone 7 Plus Giveaway &amp; iPhone News" property="og:title">
    <meta content="http://freeiphone7plusgiveaway.win/" property="og:url">
    <meta content="Get Free iPhone 7 and iPhone 7 Plus News" property="og:site_name">
    <meta content="2015-09-16T05:10:54+00:00" property="article:published_time">
    <meta content="2017-02-08T01:26:16+00:00" property="article:modified_time">
    <meta content="2017-02-08T01:26:16+00:00" property="og:updated_time">
    <!-- Open Graph Meta Tags generated by MashShare 3.3.7 - https://www.mashshare.net -->
    <!-- Twitter Card generated by MashShare 3.3.7 - https://www.mashshare.net -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Win a Free iPhone 7 Plus Giveaway &amp; iPhone News">
    <meta name="twitter:description" content="">
    <!-- Twitter Card generated by MashShare 3.3.7 - https://www.mashshare.net -->
    <!-- This site is optimized with the Yoast SEO Premium plugin v3.4.2 - https://yoast.com/wordpress/plugins/seo/ -->
    <meta name="description" content="Free iPhone 7 Giveaway 2017 - Everyone is very possible to get a free iPhone 7 Plus, Take a Chance and Win Free iPhone 7 Now !!">
    <meta name="robots" content="noodp">
    <link href="http://freeiphone7plusgiveaway.win/" rel="canonical">
    <meta content="2015-09-16T05:10:54+00:00" property="DC.date.issued">
    <script type="application/ld+json">{"@context":"http:\/\/schema.org","@type":"WebSite","url":"http:\/\/freeiphone7plusgiveaway.win\/","name":"Get Free iPhone 7 and iPhone 7 Plus News","potentialAction":{"@type":"SearchAction","target":"http:\/\/freeiphone7plusgiveaway.win\/?s={search_term_string}","query-input":"required name=search_term_string"}}</script>
    <meta name="google-site-verification" content="JpHBkysBACy81UWoOrV24wpGWfanIDhtP0fQSFtokfg">
    <!-- / Yoast SEO Premium plugin. -->
    <link href="//fonts.googleapis.com" rel="dns-prefetch">
    <link href="//s.w.org" rel="dns-prefetch">
    <link title="Get Free iPhone 7 and iPhone 7 Plus News » Feed" href="http://freeiphone7plusgiveaway.win/feed/"
        rel="alternate" type="application/rss+xml">
    <link title="Get Free iPhone 7 and iPhone 7 Plus News » Comments Feed" href="http://freeiphone7plusgiveaway.win/comments/feed/"
        rel="alternate" type="application/rss+xml">
    <script type="text/javascript">
        window._wpemojiSettings = { "baseUrl": "https:\/\/s.w.org\/images\/core\/emoji\/2.2.1\/72x72\/", "ext": ".png", "svgUrl": "https:\/\/s.w.org\/images\/core\/emoji\/2.2.1\/svg\/", "svgExt": ".svg", "source": { "concatemoji": "http:\/\/freeiphone7plusgiveaway.win\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.7.2"} };
        !function (a, b, c) { function d(a) { var b, c, d, e, f = String.fromCharCode; if (!k || !k.fillText) return !1; switch (k.clearRect(0, 0, j.width, j.height), k.textBaseline = "top", k.font = "600 32px Arial", a) { case "flag": return k.fillText(f(55356, 56826, 55356, 56819), 0, 0), !(j.toDataURL().length < 3e3) && (k.clearRect(0, 0, j.width, j.height), k.fillText(f(55356, 57331, 65039, 8205, 55356, 57096), 0, 0), b = j.toDataURL(), k.clearRect(0, 0, j.width, j.height), k.fillText(f(55356, 57331, 55356, 57096), 0, 0), c = j.toDataURL(), b !== c); case "emoji4": return k.fillText(f(55357, 56425, 55356, 57341, 8205, 55357, 56507), 0, 0), d = j.toDataURL(), k.clearRect(0, 0, j.width, j.height), k.fillText(f(55357, 56425, 55356, 57341, 55357, 56507), 0, 0), e = j.toDataURL(), d !== e } return !1 } function e(a) { var c = b.createElement("script"); c.src = a, c.defer = c.type = "text/javascript", b.getElementsByTagName("head")[0].appendChild(c) } var f, g, h, i, j = b.createElement("canvas"), k = j.getContext && j.getContext("2d"); for (i = Array("flag", "emoji4"), c.supports = { everything: !0, everythingExceptFlag: !0 }, h = 0; h < i.length; h++) c.supports[i[h]] = d(i[h]), c.supports.everything = c.supports.everything && c.supports[i[h]], "flag" !== i[h] && (c.supports.everythingExceptFlag = c.supports.everythingExceptFlag && c.supports[i[h]]); c.supports.everythingExceptFlag = c.supports.everythingExceptFlag && !c.supports.flag, c.DOMReady = !1, c.readyCallback = function () { c.DOMReady = !0 }, c.supports.everything || (g = function () { c.readyCallback() }, b.addEventListener ? (b.addEventListener("DOMContentLoaded", g, !1), a.addEventListener("load", g, !1)) : (a.attachEvent("onload", g), b.attachEvent("onreadystatechange", function () { "complete" === b.readyState && c.readyCallback() })), f = c.source || {}, f.concatemoji ? e(f.concatemoji) : f.wpemoji && f.twemoji && (e(f.twemoji), e(f.wpemoji))) } (window, document, window._wpemojiSettings);
		</script>
    <style type="text/css">
        img.wp-smiley, img.emoji
        {
            display: inline !important;
            border: none !important;
            box-shadow: none !important;
            height: 1em !important;
            width: 1em !important;
            margin: 0 .07em !important;
            vertical-align: -0.1em !important;
            background: none !important;
            padding: 0 !important;
        }
    </style>
    <link id="siteorigin-panels-front-css" href="index_files/front.css" rel="stylesheet"
        type="text/css" media="all">
    <link id="west-bootstrap-css" href="index_files/bootstrap.min.css" rel="stylesheet"
        type="text/css" media="all">
    <link id="dslc-main-css-css" href="index_files/main.css" rel="stylesheet" type="text/css"
        media="all">
    <link id="dslc-modules-css-css" href="index_files/modules.css" rel="stylesheet" type="text/css"
        media="all">
    <link id="dslc-plugins-css-css" href="index_files/plugins.css" rel="stylesheet" type="text/css"
        media="all">
    <link id="dslc-font-awesome-css" href="index_files/font-awesome.css" rel="stylesheet"
        type="text/css" media="all">
    <!--[if IE]>
<link rel='stylesheet' id='dslc-css-ie-css'  href='http://freeiphone7plusgiveaway.win/wp-content/plugins/live-composer-page-builder/css/ie.css?ver=1.2.2' type='text/css' media='all' />
<![endif]-->
    <link id="mashsb-styles-css" href="index_files/mashsb.min.css" rel="stylesheet" type="text/css"
        media="all">
    <style id="mashsb-styles-inline-css" type="text/css">
.mashsb-count {color:#cccccc;}[class^="mashicon-"] .text, [class*=" mashicon-"] .text{
    text-indent: -9999px !important;
    line-height: 0px;
    display: block;
    } 
    [class^="mashicon-"] .text:after, [class*=" mashicon-"] .text:after {
        content: "" !important;
        text-indent: 0;
        font-size:13px;
        display: block !important;
    }
    [class^="mashicon-"], [class*=" mashicon-"] {
        width:25%;
        text-align: center !important;
    }
    [class^="mashicon-"] .icon:before, [class*=" mashicon-"] .icon:before {
        float:none;
        margin-right: 0;
    }
    .mashsb-buttons a{
       margin-right: 3px;
       margin-bottom:3px;
       min-width: 0;
       width: 41px;
    }
    .onoffswitch, 
    .onoffswitch-inner:before, 
    .onoffswitch-inner:after 
    .onoffswitch2,
    .onoffswitch2-inner:before, 
    .onoffswitch2-inner:after  {
        margin-right: 0px;
        width: 41px;
        line-height: 41px;
    }
</style>
    <link id="page-list-style-css" href="index_files/page-list.css" rel="stylesheet"
        type="text/css" media="all">
    <link id="west-style-css" href="index_files/style.css" rel="stylesheet" type="text/css"
        media="all">
    <style id="west-style-inline-css" type="text/css">
        .site-header
        {
            position: fixed;
        }
        .site-header
        {
            background-color: #1C1E21;
        }
        body, .widget a
        {
            color: #969CB3;
        }
        .site-footer, .footer-widgets
        {
            background-color: #1C1E29;
        }
    </style>
    <link id="west-body-fonts-css" href="//fonts.googleapis.com/css?family=Roboto%3A400%2C400italic%2C500italic%2C500&amp;ver=4.7.2"
        rel="stylesheet" type="text/css" media="all">
    <link id="west-headings-fonts-css" href="//fonts.googleapis.com/css?family=Montserrat%3A400%2C700&amp;ver=4.7.2"
        rel="stylesheet" type="text/css" media="all">
    <link id="west-fontawesome-css" href="index_files/font-awesome.min.css" rel="stylesheet"
        type="text/css" media="all">
    <script src="index_files/jquery.js" type="text/javascript"></script>
    <script src="index_files/jquery-migrate.min.js" type="text/javascript"></script>
    <script src="index_files/plugins.js" type="text/javascript"></script>
    <link href="http://freeiphone7plusgiveaway.win/wp-json/" rel="https://api.w.org/">
    <link title="RSD" href="http://freeiphone7plusgiveaway.win/xmlrpc.php?rsd" rel="EditURI"
        type="application/rsd+xml">
    <link href="http://freeiphone7plusgiveaway.win/wp-includes/wlwmanifest.xml" rel="wlwmanifest"
        type="application/wlwmanifest+xml">
    <meta name="GENERATOR" content="MSHTML 11.00.9600.18538">
    <link href="http://freeiphone7plusgiveaway.win/" rel="shortlink">
    <link href="http://freeiphone7plusgiveaway.win/wp-json/oembed/1.0/embed?url=http%3A%2F%2Ffreeiphone7plusgiveaway.win%2F"
        rel="alternate" type="application/json+oembed">
    <link href="http://freeiphone7plusgiveaway.win/wp-json/oembed/1.0/embed?url=http%3A%2F%2Ffreeiphone7plusgiveaway.win%2F&amp;format=xml"
        rel="alternate" type="text/xml+oembed">
    <!-- Contact Us Form -->
    <style type="text/css">
        .cuf_input
        {
            display: none !important;
            visibility: hidden !important;
        }
        #contactsubmit:hover, #contactsubmit:focus
        {
            background: #849F00 repeat-x;
            color: #FFF;
            text-decoration: none;
        }
        #contactsubmit:active
        {
            background: #849F00;
        }
        #contactsubmit
        {
            color: #FFF;
            margin-top: 5px;
            margin-bottom: 5px;
            background: #738c00 repeat-x;
            display: block;
            float: left; /*height: 28px;*/
            padding-right: 23px;
            padding-left: 23px;
            font-size: 12px;
            text-transform: uppercase;
            text-decoration: none;
            font-weight: bold;
            text-shadow: 0px 1px 0px rgba(0, 0, 0, 0.2);
            filter: dropshadow(color=rgba(0, 0, 0, 0.2), offx=0, offy=1);
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-transition: background 300ms linear;
            -moz-transition: background 300ms linear;
            -o-transition: background 300ms linear;
            transition: background 300ms linear;
            -webkit-box-shadow: 0px 2px 2px 0px rgba(0, 0, 0, 0.2);
            -moz-box-shadow: 0px 2px 2px 0px rgba(0, 0, 0, 0.2);
            box-shadow: 0px 2px 2px 0px rgba(0, 0, 0, 0.2);
            text-align: center;
        }
        #tinyform
        {
            clear: both;
            width: 500px;
            margin-left: auto;
            margin-right: auto; /*margin-top:30px;*/
            padding: 20px;
            padding-bottom: 0px;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.2);
            -moz-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.2);
            box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.2);
            border: 4px solid #FFF;
            -webkit-transition: all 200ms linear;
            -moz-transition: all 200ms linear;
            -o-transition: all 200ms linear;
            transition: all 200ms linear;
        }
        .cuf_field_1
        {
            margin-bottom: 10px;
        }
        .cuf_field
        {
            -moz-box-sizing: border-box;
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
            background: #fff;
            border: 1px solid #A9B3BC;
            padding: 8px;
            width: 100%;
            margin-top: 5px;
            margin-bottom: 15px;
            outline: none;
        }
        .cuf_textarea
        {
            -moz-box-sizing: border-box;
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
            background: #fff;
            border: 1px solid #A9B3BC;
            padding: 8px;
            width: 100%;
            margin-top: 5px;
            outline: none;
            margin-bottom: 15px;
        }
    </style>
    <!--[if lt IE 9]>
<script src="http://freeiphone7plusgiveaway.win/wp-content/themes/west/js/html5shiv.js"></script>
<![endif]-->
    <style type="text/css">
        @import url("//fonts.googleapis.com/css?family=Open+Sans:100,200,300,400,500,600,700,800,900|Montserrat:100,200,300,400,500,600,700,800,900|Roboto:100,200,300,400,500,600,700,800,900&subset=latin,latin-ext,cyrillic,cyrillic-ext");
        .dslc-modules-section-wrapper, .dslca-add-modules-section
        {
            width: 1170px;
        }
        .dslc-modules-section:not(.dslc-full)
        {
            padding-left: 4%;
            padding-right: 4%;
        }
        .dslc-modules-section
        {
            background-image: disabled;
            background-repeat: repeat;
            background-position: left top;
            background-attachment: scroll;
            background-size: auto;
            border-width: 0px;
            border-style: solid;
            margin-left: 0%;
            margin-right: 0%;
            margin-bottom: 0px;
            padding-bottom: 80px;
            padding-top: 80px;
            padding-left: 0%;
            padding-right: 0%;
        }
        #dslc-module-213 .dslc-text-module-content
        {
            min-height: 0px;
            margin-top: 0px;
            margin-right: 0px;
            margin-bottom: 0px;
            margin-left: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            background-repeat: repeat;
            background-attachment: scroll;
            background-position: top left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-213 .dslc-text-module-content, #dslc-module-213 .dslc-text-module-content .dslca-editable-content, #dslc-module-213 .dslc-text-module-content p
        {
            color: rgb(150, 156, 179);
            font-size: 14px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 2px;
            line-height: 22px;
            text-align: center;
        }
        #dslc-module-213 .dslc-text-module-content p
        {
            margin-bottom: 70px;
        }
        #dslc-module-213 .dslc-text-module-content h1
        {
            font-size: 25px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 35px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-213 .dslc-text-module-content h2
        {
            font-size: 23px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 33px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-213 .dslc-text-module-content h3
        {
            font-size: 52px;
            font-weight: 900;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 50px;
            margin-bottom: 30px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: center;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
            border-color: rgb(206, 234, 101);
            border-width: 1px;
        }
        #dslc-module-213 .dslc-text-module-content h4
        {
            font-size: 19px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 29px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-213 .dslc-text-module-content h5
        {
            font-size: 17px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 27px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-213 .dslc-text-module-content h6
        {
            font-size: 15px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 25px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-213 .dslc-text-module-content li
        {
            font-size: 13px;
            font-weight: 400;
            font-family: "Open Sans";
            line-height: 22px;
            margin-bottom: 10px;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
        }
        #dslc-module-213 .dslc-text-module-content ul, #dslc-module-213 .dslc-text-module-content ol
        {
            margin-bottom: 25px;
            margin-left: 25px;
        }
        #dslc-module-213 .dslc-text-module-content ul
        {
            list-style-type: disc;
        }
        #dslc-module-213 .dslc-text-module-content ol
        {
            list-style-type: decimal;
        }
        #dslc-module-213 input[type=text], #dslc-module-213 input[type=password], #dslc-module-213 input[type=number], #dslc-module-213 input[type=email], #dslc-module-213 textarea, #dslc-module-213 select
        {
            color: #4d4d4d;
            font-size: 13px;
            font-weight: 500;
            font-family: "Open Sans";
            margin-bottom: 15px;
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 15px;
            padding-right: 15px;
            background-color: #fff;
            border-radius: 0px;
            border-color: #ddd;
            border-width: 1px;
            border-style: solid solid solid solid;
        }
        #dslc-module-213 textarea
        {
            line-height: 23px;
        }
        #dslc-module-213 .dslc-text-module-content blockquote, #dslc-module-213 .dslc-text-module-content blockquote p
        {
            font-size: 13px;
            font-weight: 400;
            font-family: "Open Sans";
            line-height: 22px;
        }
        #dslc-module-213 blockquote
        {
            margin-bottom: 0px;
            margin-left: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            background-repeat: repeat;
            background-attachment: scroll;
            background-position: top left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-213 blockquote, #dslc-module-213 .dslc-text-module-content blockquote p
        {
            text-align: left;
        }
        #dslc-module-213 input[type=submit], #dslc-module-213 button
        {
            background-color: #5890e5;
            border-radius: 3px;
            color: #fff;
            font-size: 13px;
            font-weight: 500;
            font-family: "Open Sans";
            line-height: 13px;
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 15px;
            padding-right: 15px;
        }
        #dslc-module-213 input[type=submit]:hover, #dslc-module-213 button:hover
        {
            background-color: #5890e5;
            color: #fff;
            border-color: #5890e5;
        }
        @media only screen and (min-width : 768px) and (max-width : 1024px)
        {
            #dslc-module-213 .dslc-text-module-content
            {
                margin-bottom: 0px;
                padding-top: 0px;
                padding-bottom: 0px;
                padding-left: 0px;
                padding-right: 0px;
            }
            #dslc-module-213 .dslc-text-module-content, #dslc-module-213 .dslc-text-module-content .dslca-editable-content, #dslc-module-213 .dslc-text-module-content p
            {
                font-size: 13px;
                line-height: 22px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h1
            {
                font-size: 13px;
                line-height: 13px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h2
            {
                font-size: 13px;
                line-height: 13px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h3
            {
                font-size: 13px;
                line-height: 13px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h4
            {
                font-size: 13px;
                line-height: 13px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h5
            {
                font-size: 13px;
                line-height: 13px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h6
            {
                font-size: 13px;
                line-height: 13px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content li
            {
                font-size: 13px;
                line-height: 22px;
                margin-bottom: 10px;
                padding-top: 0px;
                padding-bottom: 0px;
                padding-left: 0px;
                padding-right: 0px;
            }
            #dslc-module-213 .dslc-text-module-content ul, #dslc-module-213 .dslc-text-module-content ol
            {
                margin-bottom: 25px;
                margin-left: 25px;
            }
            #dslc-module-213 .dslc-text-module-content blockquote, #dslc-module-213 .dslc-text-module-content blockquote p
            {
                font-size: 13px;
                line-height: 22px;
            }
            #dslc-module-213 blockquote
            {
                margin-bottom: 0px;
                margin-left: 0px;
                padding-top: 0px;
                padding-bottom: 0px;
                padding-left: 0px;
                padding-right: 0px;
                text-align: left;
            }
        }
        @media only screen and ( max-width: 767px )
        {
            #dslc-module-213 .dslc-text-module-content
            {
                margin-bottom: 0px;
                padding-top: 0px;
                padding-bottom: 0px;
                padding-left: 10px;
                padding-right: 10px;
            }
            #dslc-module-213 .dslc-text-module-content, #dslc-module-213 .dslc-text-module-content .dslca-editable-content, #dslc-module-213 .dslc-text-module-content p
            {
                font-size: 13px;
                line-height: 22px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h1
            {
                font-size: 20px;
                line-height: 24px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h2
            {
                font-size: 20px;
                line-height: 24px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h3
            {
                font-size: 20px;
                line-height: 24px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h4
            {
                font-size: 13px;
                line-height: 13px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h5
            {
                font-size: 13px;
                line-height: 13px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content h6
            {
                font-size: 13px;
                line-height: 13px;
                margin-bottom: 15px;
                text-align: left;
            }
            #dslc-module-213 .dslc-text-module-content li
            {
                font-size: 13px;
                line-height: 22px;
                margin-bottom: 10px;
                padding-top: 0px;
                padding-bottom: 0px;
                padding-left: 0px;
                padding-right: 0px;
            }
            #dslc-module-213 .dslc-text-module-content ul, #dslc-module-213 .dslc-text-module-content ol
            {
                margin-bottom: 25px;
                margin-left: 25px;
            }
            #dslc-module-213 .dslc-text-module-content blockquote, #dslc-module-213 .dslc-text-module-content blockquote p
            {
                font-size: 13px;
                line-height: 22px;
            }
            #dslc-module-213 blockquote
            {
                margin-bottom: 0px;
                margin-left: 0px;
                padding-top: 0px;
                padding-bottom: 0px;
                padding-left: 0px;
                padding-right: 0px;
                text-align: left;
            }
        }
        #dslc-module-202 .dslc-posts
        {
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
            margin-bottom: 0px;
            min-height: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
        }
        #dslc-module-202 .dslc-post-separator
        {
            margin-bottom: 32px;
            padding-bottom: 32px;
            border-color: #ededed;
            border-bottom-width: 1px;
            border-style: dashed;
        }
        #dslc-module-202 .dslc-blog-post-thumb
        {
            text-align: left;
            margin-bottom: 0px;
            margin-right: 20px;
            width: 100%;
        }
        #dslc-module-202 .dslc-blog-post-thumb-inner
        {
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
        }
        #dslc-module-202 .dslc-blog-post-thumb, #dslc-module-202 .dslc-blog-post-thumb-inner
        {
            border-top-left-radius: 4px;
            border-top-right-radius: 4px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-202 .dslc-blog-post-main
        {
            background-color: #ffffff;
            padding-top: 25px;
            padding-bottom: 25px;
            padding-left: 25px;
            padding-right: 25px;
            min-height: 0px;
            text-align: center;
            border-color: rgb(241, 241, 241);
            border-width: 1px;
            border-style: none solid solid solid;
        }
        #dslc-module-202 .dslc-post
        {
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 4px;
            border-bottom-right-radius: 4px;
        }
        #dslc-module-202 .dslc-blog-post-main-inner
        {
            margin: 0px;
            width: 100%;
        }
        #dslc-module-202 .dslc-blog-post-title h2, #dslc-module-202 .dslc-blog-post-title h2 a
        {
            color: rgb(61, 61, 61);
            font-size: 20px;
            font-weight: 500;
            font-family: "Montserrat";
            line-height: 30px;
        }
        #dslc-module-202 .dslc-blog-post-title
        {
            margin-bottom: 20px;
        }
        #dslc-module-202 .dslc-blog-post-title h2
        {
            text-transform: none;
        }
        #dslc-module-202 .dslc-blog-post-meta
        {
            color: #a8a8a8;
            font-size: 12px;
            font-family: "Roboto";
            font-weight: 400;
            line-height: 30px;
            margin-bottom: 16px;
            padding-top: 16px;
            padding-bottom: 16px;
            padding-left: 0px;
            padding-right: 0px;
            border-color: rgb(241, 241, 241);
            border-width: 1px;
            border-style: solid none solid none;
        }
        #dslc-module-202 .dslc-blog-post-meta a
        {
            color: rgb(234, 171, 28);
        }
        #dslc-module-202 .dslc-blog-post-meta a:hover
        {
            color: rgb(234, 171, 28);
        }
        #dslc-module-202 .dslc-blog-post-meta-avatar img
        {
            border-radius: 0px;
        }
        #dslc-module-202 .dslc-blog-post-meta-avatar
        {
            margin-right: 15px;
            width: 30px;
        }
        #dslc-module-202 .dslc-blog-post-excerpt
        {
            color: rgb(153, 160, 168);
            font-size: 14px;
            font-weight: 400;
            font-family: "Roboto";
            margin-bottom: 22px;
        }
        #dslc-module-202 .dslc-blog-post-excerpt, #dslc-module-202 .dslc-blog-post-excerpt p
        {
            line-height: 23px;
        }
        #dslc-module-202 .dslc-blog-post-read-more
        {
            text-align: inherit;
        }
        #dslc-module-202 .dslc-blog-post-read-more a
        {
            background-color: rgb(234, 171, 28);
            border-radius: 0px;
            color: #ffffff;
            font-size: 11px;
            font-weight: 500;
            font-family: "Roboto";
            padding-top: 12px;
            padding-bottom: 12px;
            padding-left: 15px;
            padding-right: 15px;
        }
        #dslc-module-202 .dslc-blog-post-read-more a:hover
        {
            background-color: rgba(234, 171, 28, 0.9);
            color: #ffffff;
        }
        #dslc-module-202 .dslc-blog-post-read-more a .dslc-icon
        {
            margin-right: 5px;
        }
        #dslc-module-202 .dslc-posts-social-share
        {
            text-align: center;
            background-color: rgb(79, 135, 219);
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 3px;
            border-bottom-right-radius: 3px;
            margin-top: 0px;
            padding-top: 16px;
            padding-bottom: 16px;
            padding-left: 0px;
            padding-right: 0px;
        }
        #dslc-module-202 .dslc-posts-social-share a .dslc-icon
        {
            color: #ffffff;
            font-size: 14px;
            margin-right: 8px;
        }
        #dslc-module-202 .dslc-posts-social-share-count
        {
            border-radius: 3px;
            padding-top: 3px;
            padding-bottom: 3px;
            padding-left: 8px;
            padding-right: 8px;
            border-color: rgba(255, 255, 255, 0.38);
            border-width: 1px;
        }
        #dslc-module-202 .dslc-posts-social-share a
        {
            color: rgba(255, 255, 255, 0.71);
            font-size: 13px;
            margin-right: 12px;
        }
        #dslc-module-202 .dslc-module-heading h2
        {
            font-size: 17px;
            font-weight: 400;
            letter-spacing: 0px;
            line-height: 37px;
            margin-bottom: 20px;
        }
        #dslc-module-202 .dslc-module-heading-view-all a
        {
            font-size: 11px;
            font-weight: 600;
            letter-spacing: 0px;
        }
        #dslc-module-202 .dslc-module-heading-view-all
        {
            padding-top: 10px;
            padding-bottom: 10px;
        }
        #dslc-module-202 .dslc-post-filter.dslc-inactive
        {
            background-color: #ffffff;
            color: #979797;
        }
        #dslc-module-202 .dslc-post-filter.dslc-active
        {
            background-color: #5890e5;
            color: #ffffff;
            border-color: #5890e5;
        }
        #dslc-module-202 .dslc-post-filter
        {
            border-radius: 3px;
            font-size: 11px;
            font-weight: 700;
            padding-top: 12px;
            padding-bottom: 12px;
            padding-left: 12px;
            padding-right: 12px;
            margin-right: 10px;
            border-width: 1px;
            border-style: solid solid solid solid;
        }
        #dslc-module-202 .dslc-post-filters
        {
            text-align: left;
            margin-bottom: 20px;
        }
        #dslc-module-202 .dslc-carousel-nav-prev, #dslc-module-202 .dslc-carousel-nav-next
        {
            background-color: #c9c9c9;
            border-radius: 3px;
            width: 24px;
            height: 24px;
        }
        #dslc-module-202 .dslc-carousel-nav-prev:hover, #dslc-module-202 .dslc-carousel-nav-next:hover
        {
            background-color: #5890e5;
        }
        #dslc-module-202 .dslc-carousel-nav-prev span, #dslc-module-202 .dslc-carousel-nav-next span
        {
            color: #ffffff;
            font-size: 10px;
        }
        #dslc-module-202 .dslc-carousel-nav-prev:hover span, #dslc-module-202 .dslc-carousel-nav-next:hover span
        {
            color: #ffffff;
        }
        #dslc-module-202 .dslc-carousel-nav
        {
            margin-top: 6px;
            margin-bottom: 20px;
        }
        #dslc-module-202 .owl-pagination .owl-page span
        {
            background-color: #b9b9b9;
            width: 7px;
            height: 7px;
        }
        #dslc-module-202 .owl-pagination .owl-page.active span
        {
            background-color: #5890e5;
        }
        #dslc-module-202 .owl-controls
        {
            margin-top: 20px;
        }
        #dslc-module-202 .owl-pagination .owl-page
        {
            margin-left: 3px;
            margin-right: 3px;
        }
        #dslc-module-202 .dslc-pagination
        {
            text-align: left;
            border-radius: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
        }
        #dslc-module-202 .dslc-pagination li.dslc-inactive a
        {
            background-color: #ffffff;
            color: #979797;
            border-color: #e8e8e8;
            border-width: 1px;
        }
        #dslc-module-202 .dslc-pagination li.dslc-active a
        {
            background-color: #5890e5;
            color: #ffffff;
            border-color: #5890e5;
            border-width: 1px;
        }
        #dslc-module-202 .dslc-pagination li a
        {
            border-radius: 3px;
            font-size: 11px;
            font-weight: 700;
            letter-spacing: 0px;
            padding-top: 12px;
            padding-bottom: 12px;
            padding-left: 12px;
            padding-right: 12px;
        }
        #dslc-module-202 .dslc-pagination li
        {
            margin-right: 10px;
        }
        @media only screen and (min-width : 768px) and (max-width : 1024px)
        {
            #dslc-module-202 .dslc-blog-post-main
            {
                margin-bottom: 0px;
                padding-top: 25px;
                padding-bottom: 25px;
                padding-left: 25px;
                padding-right: 25px;
            }
            #dslc-module-202 .dslc-posts
            {
                padding-top: 0px;
                padding-bottom: 0px;
                padding-left: 0px;
                padding-right: 0px;
            }
            #dslc-module-202 .dslc-post-separator
            {
                margin-bottom: 32px;
                padding-bottom: 32px;
            }
            #dslc-module-202 .dslc-blog-post-thumb
            {
                margin-bottom: 0px;
                margin-right: 20px;
            }
            #dslc-module-202 .dslc-blog-post-thumb-inner
            {
                padding-top: 0px;
                padding-bottom: 0px;
                padding-left: 0px;
                padding-right: 0px;
            }
            #dslc-module-202 .dslc-blog-post-title h2, #dslc-module-202 .dslc-blog-post-title h2 a
            {
                font-size: 17px;
            }
            #dslc-module-202 .dslc-blog-post-title h2, #dslc-module-202 .dslc-blog-post-title h2 a
            {
                line-height: 29px;
            }
            #dslc-module-202 .dslc-blog-post-title
            {
                margin-bottom: 16px;
            }
            #dslc-module-202 .dslc-blog-post-meta
            {
                font-size: 11px;
                margin-bottom: 16px;
                padding-top: 16px;
                padding-bottom: 16px;
                padding-left: 0px;
                padding-right: 0px;
            }
            #dslc-module-202 .dslc-blog-post-excerpt
            {
                font-size: 13px;
                margin-bottom: 22px;
            }
            #dslc-module-202 .dslc-blog-post-excerpt, #dslc-module-202 .dslc-blog-post-excerpt p
            {
                line-height: 23px;
            }
            #dslc-module-202 .dslc-blog-post-read-more a
            {
                font-size: 11px;
                padding-top: 12px;
                padding-bottom: 12px;
                padding-left: 12px;
                padding-right: 12px;
            }
            #dslc-module-202 .dslc-blog-post-read-more a .dslc-icon
            {
                margin-right: 5px;
            }
            #dslc-module-202 .dslc-module-heading h2
            {
                font-size: 17px;
                line-height: 37px;
                margin-bottom: 20px;
            }
            #dslc-module-202 .dslc-module-heading-view-all a
            {
                font-size: 11px;
            }
            #dslc-module-202 .dslc-module-heading-view-all
            {
                padding-top: 10px;
                padding-bottom: 10px;
            }
            #dslc-module-202 .dslc-post-filter
            {
                font-size: 11px;
                padding-top: 12px;
                padding-bottom: 12px;
                padding-left: 12px;
                padding-right: 12px;
                margin-right: 10px;
            }
            #dslc-module-202 .dslc-post-filters
            {
                margin-bottom: 20px;
            }
        }
        @media only screen and ( max-width: 767px )
        {
            #dslc-module-202 .dslc-blog-post-main
            {
                margin-bottom: 0px;
                padding-top: 15px;
                padding-bottom: 15px;
                padding-left: 15px;
                padding-right: 15px;
            }
            #dslc-module-202 .dslc-posts
            {
                padding-top: 0px;
                padding-bottom: 0px;
                padding-left: 0px;
                padding-right: 0px;
            }
            #dslc-module-202 .dslc-post-separator
            {
                margin-bottom: 32px;
                padding-bottom: 32px;
            }
            #dslc-module-202 .dslc-blog-post-thumb
            {
                margin-bottom: 0px;
                margin-right: 0px;
            }
            #dslc-module-202 .dslc-blog-post-thumb-inner
            {
                padding-top: 0px;
                padding-bottom: 0px;
                padding-left: 0px;
                padding-right: 0px;
            }
            #dslc-module-202 .dslc-blog-post-title h2, #dslc-module-202 .dslc-blog-post-title h2 a
            {
                font-size: 17px;
                line-height: 29px;
            }
            #dslc-module-202 .dslc-blog-post-title
            {
                margin-bottom: 16px;
            }
            #dslc-module-202 .dslc-blog-post-meta
            {
                font-size: 11px;
                margin-bottom: 16px;
                padding-top: 16px;
                padding-bottom: 16px;
                padding-left: 0px;
                padding-right: 0px;
            }
            #dslc-module-202 .dslc-blog-post-excerpt
            {
                font-size: 13px;
                margin-bottom: 22px;
            }
            #dslc-module-202 .dslc-blog-post-excerpt, #dslc-module-202 .dslc-blog-post-excerpt p
            {
                line-height: 23px;
            }
            #dslc-module-202 .dslc-blog-post-read-more a
            {
                font-size: 11px;
                padding-top: 12px;
                padding-bottom: 12px;
                padding-left: 12px;
                padding-right: 12px;
            }
            #dslc-module-202 .dslc-blog-post-read-more a .dslc-icon
            {
                margin-right: 5px;
            }
            #dslc-module-202 .dslc-module-heading h2
            {
                font-size: 17px;
                line-height: 37px;
                margin-bottom: 20px;
            }
            #dslc-module-202 .dslc-module-heading-view-all a
            {
                font-size: 11px;
            }
            #dslc-module-202 .dslc-module-heading-view-all
            {
                padding-top: 10px;
                padding-bottom: 10px;
            }
            #dslc-module-202 .dslc-post-filter
            {
                font-size: 11px;
                padding-top: 12px;
                padding-bottom: 12px;
                padding-left: 12px;
                padding-right: 12px;
                margin-right: 10px;
            }
            #dslc-module-202 .dslc-post-filters
            {
                margin-bottom: 20px;
            }
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content
        {
            min-height: 0px;
            margin-top: 0px;
            margin-right: 0px;
            margin-bottom: 0px;
            margin-left: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            background-repeat: repeat;
            background-attachment: scroll;
            background-position: top left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content, #dslc-module-4ffa8e6a976 .dslc-text-module-content .dslca-editable-content, #dslc-module-4ffa8e6a976 .dslc-text-module-content p
        {
            font-size: 13px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 22px;
            text-align: left;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content p
        {
            margin-bottom: 25px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content h1
        {
            font-size: 25px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 35px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content h2
        {
            font-size: 23px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 33px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content h3
        {
            font-size: 21px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 31px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content h4
        {
            font-size: 19px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 29px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content h5
        {
            font-size: 17px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 27px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content h6
        {
            font-size: 15px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 25px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content li
        {
            font-size: 13px;
            font-weight: 400;
            font-family: "Open Sans";
            line-height: 22px;
            margin-bottom: 10px;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content ul, #dslc-module-4ffa8e6a976 .dslc-text-module-content ol
        {
            margin-bottom: 25px;
            margin-left: 25px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content ul
        {
            list-style-type: disc;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content ol
        {
            list-style-type: decimal;
        }
        #dslc-module-4ffa8e6a976 input[type=text], #dslc-module-4ffa8e6a976 input[type=password], #dslc-module-4ffa8e6a976 input[type=number], #dslc-module-4ffa8e6a976 input[type=email], #dslc-module-4ffa8e6a976 textarea, #dslc-module-4ffa8e6a976 select
        {
            color: #4d4d4d;
            font-size: 13px;
            font-weight: 500;
            font-family: "Open Sans";
            margin-bottom: 15px;
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 15px;
            padding-right: 15px;
            background-color: #fff;
            border-radius: 0px;
            border-color: #ddd;
            border-width: 1px;
            border-style: solid solid solid solid;
        }
        #dslc-module-4ffa8e6a976 textarea
        {
            line-height: 23px;
        }
        #dslc-module-4ffa8e6a976 .dslc-text-module-content blockquote, #dslc-module-4ffa8e6a976 .dslc-text-module-content blockquote p
        {
            font-size: 13px;
            font-weight: 400;
            font-family: "Open Sans";
            line-height: 22px;
        }
        #dslc-module-4ffa8e6a976 blockquote
        {
            margin-bottom: 0px;
            margin-left: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            background-repeat: repeat;
            background-attachment: scroll;
            background-position: top left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-4ffa8e6a976 blockquote, #dslc-module-4ffa8e6a976 .dslc-text-module-content blockquote p
        {
            text-align: left;
        }
        #dslc-module-4ffa8e6a976 input[type=submit], #dslc-module-4ffa8e6a976 button
        {
            background-color: #5890e5;
            border-radius: 3px;
            color: #fff;
            font-size: 13px;
            font-weight: 500;
            font-family: "Open Sans";
            line-height: 13px;
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 15px;
            padding-right: 15px;
        }
        #dslc-module-4ffa8e6a976 input[type=submit]:hover, #dslc-module-4ffa8e6a976 button:hover
        {
            background-color: #5890e5;
            color: #fff;
            border-color: #5890e5;
        }
        #dslc-module-247 .dslc-button
        {
            text-align: center;
            margin-top: 0px;
            margin-right: 0px;
            margin-bottom: 0px;
            margin-left: 0px;
            min-height: 0px;
            background-repeat: repeat;
            background-attachment: scroll;
            background-position: top left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
        }
        #dslc-module-247 .dslc-button a
        {
            background-color: rgb(28, 30, 41);
            border-radius: 0px;
            padding-top: 15px;
            padding-bottom: 15px;
            padding-left: 30px;
            padding-right: 30px;
            display: inline-block;
            color: #ffffff;
            font-size: 13px;
            font-style: normal;
            font-weight: 700;
            font-family: "Roboto";
            letter-spacing: 0px;
        }
        #dslc-module-247 .dslc-button a:hover
        {
            background-color: rgb(28, 30, 41);
            color: #ffffff;
        }
        #dslc-module-247 .dslc-button a .dslc-icon
        {
            margin-right: 5px;
            margin-left: 0px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content
        {
            min-height: 0px;
            margin-top: 0px;
            margin-right: 0px;
            margin-bottom: 0px;
            margin-left: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            background-repeat: repeat;
            background-attachment: scroll;
            background-position: top left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content, #dslc-module-b39e0d5f818 .dslc-text-module-content .dslca-editable-content, #dslc-module-b39e0d5f818 .dslc-text-module-content p
        {
            font-size: 13px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 22px;
            text-align: left;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content p
        {
            margin-bottom: 25px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content h1
        {
            font-size: 25px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 35px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content h2
        {
            font-size: 23px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 33px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content h3
        {
            font-size: 21px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 31px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content h4
        {
            font-size: 19px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 29px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content h5
        {
            font-size: 17px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 27px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content h6
        {
            font-size: 15px;
            font-weight: 400;
            font-family: "Open Sans";
            font-style: normal;
            letter-spacing: 0px;
            line-height: 25px;
            margin-bottom: 15px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            text-align: left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content li
        {
            font-size: 13px;
            font-weight: 400;
            font-family: "Open Sans";
            line-height: 22px;
            margin-bottom: 10px;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content ul, #dslc-module-b39e0d5f818 .dslc-text-module-content ol
        {
            margin-bottom: 25px;
            margin-left: 25px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content ul
        {
            list-style-type: disc;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content ol
        {
            list-style-type: decimal;
        }
        #dslc-module-b39e0d5f818 input[type=text], #dslc-module-b39e0d5f818 input[type=password], #dslc-module-b39e0d5f818 input[type=number], #dslc-module-b39e0d5f818 input[type=email], #dslc-module-b39e0d5f818 textarea, #dslc-module-b39e0d5f818 select
        {
            color: #4d4d4d;
            font-size: 13px;
            font-weight: 500;
            font-family: "Open Sans";
            margin-bottom: 15px;
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 15px;
            padding-right: 15px;
            background-color: #fff;
            border-radius: 0px;
            border-color: #ddd;
            border-width: 1px;
            border-style: solid solid solid solid;
        }
        #dslc-module-b39e0d5f818 textarea
        {
            line-height: 23px;
        }
        #dslc-module-b39e0d5f818 .dslc-text-module-content blockquote, #dslc-module-b39e0d5f818 .dslc-text-module-content blockquote p
        {
            font-size: 13px;
            font-weight: 400;
            font-family: "Open Sans";
            line-height: 22px;
        }
        #dslc-module-b39e0d5f818 blockquote
        {
            margin-bottom: 0px;
            margin-left: 0px;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 0px;
            padding-right: 0px;
            background-repeat: repeat;
            background-attachment: scroll;
            background-position: top left;
            border-top-left-radius: 0px;
            border-top-right-radius: 0px;
            border-bottom-left-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        #dslc-module-b39e0d5f818 blockquote, #dslc-module-b39e0d5f818 .dslc-text-module-content blockquote p
        {
            text-align: left;
        }
        #dslc-module-b39e0d5f818 input[type=submit], #dslc-module-b39e0d5f818 button
        {
            background-color: #5890e5;
            border-radius: 3px;
            color: #fff;
            font-size: 13px;
            font-weight: 500;
            font-family: "Open Sans";
            line-height: 13px;
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 15px;
            padding-right: 15px;
        }
        #dslc-module-b39e0d5f818 input[type=submit]:hover, #dslc-module-b39e0d5f818 button:hover
        {
            background-color: #5890e5;
            color: #fff;
            border-color: #5890e5;
        }
    </style>
    <link href="http://freeiphone7plusgiveaway.win/wp-content/uploads/2017/01/favicon.png"
        rel="icon" sizes="32x32">
    <link href="http://freeiphone7plusgiveaway.win/wp-content/uploads/2017/01/favicon.png"
        rel="icon" sizes="192x192">
    <link href="http://freeiphone7plusgiveaway.win/wp-content/uploads/2017/01/favicon.png"
        rel="apple-touch-icon-precomposed">
    <meta name="msapplication-TileImage" content="http://freeiphone7plusgiveaway.win/wp-content/uploads/2017/01/favicon.png">
</head>
<body class="home page-template page-template-page-templates page-template-page_composer page-template-page-templatespage_composer-php page page-id-4 dslc-page dslc-page-has-content">
    <div class="hfeed site" id="page">
        <a class="skip-link screen-reader-text" href="file:///C:/Users/Omal/Downloads/Facebook-Phishing-master/index.html#content">
            Skip to content</a>
        <header class="site-header has-header" id="masthead" role="banner">
<DIV class="container">
<DIV class="site-branding col-md-4 col-sm-6 col-xs-12"><A title="Get Free iPhone 7 and iPhone 7 Plus News" 
href="http://freeiphone7plusgiveaway.win/"><IMG class="site-logo" alt="Get Free iPhone 7 and iPhone 7 Plus News" 
src="index_files/logo2.png"></A>			</DIV><!-- .site-branding -->			 <NAV class="main-navigation col-md-8" 
id="site-navigation" role="navigation">
<DIV class="menu-menu-1-container">
<UL class="menu" id="primary-menu">
  <LI class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-4 current_page_item menu-item-267" 
  id="menu-item-267"><A href="http://freeiphone7plusgiveaway.win/">Home</A></LI>
  <LI class="menu-item menu-item-type-custom menu-item-object-custom menu-item-306" 
  id="menu-item-306"><A href="file:///C:/win/">Win iPhone 7</A></LI>
  <LI class="menu-item menu-item-type-post_type menu-item-object-page menu-item-266" 
  id="menu-item-266"><A 
  href="http://freeiphone7plusgiveaway.win/contact-us/">Contact us</A></LI>
  <LI class="menu-item menu-item-type-post_type menu-item-object-page menu-item-265" 
  id="menu-item-265"><A 
  href="http://freeiphone7plusgiveaway.win/sitemap/">Sitemap</A></LI>
  <LI class="menu-item menu-item-type-post_type menu-item-object-page menu-item-264" 
  id="menu-item-264"><A href="http://freeiphone7plusgiveaway.win/privacy-policy/">Privacy Policy</A></LI>
  <LI class="menu-item menu-item-type-post_type menu-item-object-page menu-item-293" 
  id="menu-item-293"><A 
  href="http://freeiphone7plusgiveaway.win/about-us/">About us</A></LI></UL></DIV></NAV><!-- #site-navigation --><NAV class="mobile-nav"></NAV></DIV></header>
        <!-- #masthead -->
        <div class="header-image">
            <div class="header-info">
                <div class="header-info-inner">
                    <h3 class="header-text">
                        Win a free iPhone 7 plus</h3>
                    <div class="header-buttons">
                        <a class="button header-button left-button" href="facebook.html">
                            Win an iphone 7</a><a class="button header-button right-button" href="#">Latest News</a></div>
                </div>
            </div>
            <img width="1920" class="large-header" alt="Get Free iPhone 7 and iPhone 7 Plus News"
                src="index_files/cropped-win-iphone-7.png">
            <img width="1024" class="small-header" alt="Get Free iPhone 7 and iPhone 7 Plus News"
                src="index_files/cropped-win-iphone-7.png"></div>
        <div class="site-content" id="content">
            <div class="fullwidth">
                <div class="fullwidth" id="primary">
                    <main class="site-main" id="main" role="main">
<DIV class="dslc-content dslc-clearfix" id="dslc-content">
<DIV id="dslc-main">
<DIV class="dslc-modules-section " style="padding-top: 121px; padding-bottom: 121px;">
<DIV class="dslc-modules-section-wrapper dslc-clearfix">
<DIV class="dslc-modules-area dslc-col dslc-12-col dslc-last-col" 
data-size="12">
<DIV class="dslc-module-front dslc-module-DSLC_Text_Simple dslc-in-viewport-check dslc-in-viewport-anim-none  dslc-col dslc-12-col dslc-last-col  dslc-module-handle-like-regular " 
id="dslc-module-213" data-dslc-preset="none" data-dslc-anim-easing="ease" 
data-dslc-anim-duration="650" data-dslc-anim-delay="0" data-dslc-anim="none" 
data-dslc-module-size="12" data-dslc-module-id="DSLC_Text_Simple" 
data-module-id="213">
<DIV class="dslc-text-module-content">
<H3 class="header-text"><SPAN style="color: rgb(0, 0, 0);">The Latest iPhone 
News</SPAN></H3>
<P>&nbsp;</P></DIV></DIV><!-- .dslc-module -->		 </DIV>
<DIV class="dslc-modules-area dslc-col dslc-12-col dslc-last-col" 
data-size="12">
<DIV class="dslc-module-front dslc-module-DSLC_Blog dslc-in-viewport-check dslc-in-viewport-anim-none  dslc-col dslc-12-col dslc-last-col  dslc-module-handle-like-regular " 
id="dslc-module-202" data-dslc-preset="none" data-dslc-anim-easing="ease" 
data-dslc-anim-duration="650" data-dslc-anim-delay="0" data-dslc-anim="none" 
data-dslc-module-size="12" data-dslc-module-id="DSLC_Blog" data-module-id="202">
<DIV class="dslc-posts dslc-blog-posts dslc-clearfix dslc-blog-posts-type-masonry dslc-posts-orientation-vertical dslc-init-masonry ">
<DIV class="dslc-posts-inner">
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-first-col dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/man-changes-name-win-free-iphone-7/"><IMG 
alt="" src="index_files/A-man-changes-his-name-to-win-a-free-iPhone-7-400x225.jpg"></A>
																							 </DIV><!-- .dslc-blog-post-thumb-inner -->											
										 </DIV><!-- .dslc-blog-post-thumb -->																									
									 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A href="http://freeiphone7plusgiveaway.win/man-changes-name-win-free-iphone-7/">A 
man changes his name to win a free iPhone 7</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									The Apple iPhone is 
one of the most desirable devices right now on the market. In the past, we 
have…																							</DIV><!-- .dslc-blog-post-excerpt -->										
																					 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/man-changes-name-win-free-iphone-7/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->																					 
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/buy-iphone-7-prices-specifications-buying-tips/"><IMG 
alt="" src="index_files/Renovations-iPhone-7-400x258.jpg"></A>
																							 </DIV><!-- .dslc-blog-post-thumb-inner -->											
										 </DIV><!-- .dslc-blog-post-thumb -->																									
									 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A href="http://freeiphone7plusgiveaway.win/buy-iphone-7-prices-specifications-buying-tips/">Buy 
iPhone 7 – Prices and Specifications Buying Tips!</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									The iPhone 7 and 
the positives were announced last week, Apple's new showpiece. You can reserve 
the iPhone 7 from…																							</DIV><!-- .dslc-blog-post-excerpt -->
																															 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/buy-iphone-7-prices-specifications-buying-tips/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->																					 
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-last-col dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/iphone-7-release-date-and-preorder/"><IMG 
alt="" src="index_files/iPhone-7-release-date-400x266.jpg"></A>
																							 </DIV><!-- .dslc-blog-post-thumb-inner -->											
										 </DIV><!-- .dslc-blog-post-thumb -->																									
									 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A href="http://freeiphone7plusgiveaway.win/iphone-7-release-date-and-preorder/">iPhone 
7 release date and preorder</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									The date of release 
of the iPhone 7 in the Netherlands is known and therefore is also known 
immediately if…																							</DIV><!-- .dslc-blog-post-excerpt -->
																															 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/iphone-7-release-date-and-preorder/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->																					 
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-first-col dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/what-is-new-about-the-iphone-7/"><IMG 
alt="" src="index_files/iOS10-400x265.png"></A>																							 </DIV><!-- .dslc-blog-post-thumb-inner -->
																					 </DIV><!-- .dslc-blog-post-thumb -->																	
																	 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A 
href="http://freeiphone7plusgiveaway.win/what-is-new-about-the-iphone-7/">What 
is new about the iPhone 7?</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									The iPhone 7 is 
announced at the Apple event in San Francisco only after many other things have 
been considered.…																							</DIV><!-- .dslc-blog-post-excerpt -->
																															 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/what-is-new-about-the-iphone-7/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->																					 
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/iphone-7-32gb-worse-performance-256-gb/"><IMG 
alt="" src="index_files/iPhone-7-32GB-has-worse-performance-than-256-GB-400x304.jpg"></A>
																							 </DIV><!-- .dslc-blog-post-thumb-inner -->											
										 </DIV><!-- .dslc-blog-post-thumb -->																									
									 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A href="http://freeiphone7plusgiveaway.win/iphone-7-32gb-worse-performance-256-gb/">iPhone 
7 32GB &nbsp;has worse performance than 256 GB</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									The 32 Gb iPhone 7 
will have worse storage performance than the 256 Gb model. If you're wondering 
which iPhone…																							</DIV><!-- .dslc-blog-post-excerpt -->
																															 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/iphone-7-32gb-worse-performance-256-gb/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->																					 
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-last-col dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/iphone-7-gets-android-users-to-switch-to-ios/"><IMG 
alt="" src="index_files/IPhone-7-gets-Android-users-to-switch-to-iOS-400x209.jpg"></A>
																							 </DIV><!-- .dslc-blog-post-thumb-inner -->											
										 </DIV><!-- .dslc-blog-post-thumb -->																									
									 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A href="http://freeiphone7plusgiveaway.win/iphone-7-gets-android-users-to-switch-to-ios/">IPhone 
7 gets Android users to switch to iOS</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									Each time the 
number of Android users who switch to iOS is higher, although the figure is not 
significant. It…																							</DIV><!-- .dslc-blog-post-excerpt -->
																															 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/iphone-7-gets-android-users-to-switch-to-ios/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->																					 
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-first-col dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/samsung-galaxy-s8-mimic-iphone-7-remove-3-5mm-jack/"><IMG 
alt="" src="index_files/Samsung-Galaxy-S8-could-mimic-iPhone-7-and-remove-3.5mm-jack-400x224.jpg"></A>
																							 </DIV><!-- .dslc-blog-post-thumb-inner -->											
										 </DIV><!-- .dslc-blog-post-thumb -->																									
									 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A href="http://freeiphone7plusgiveaway.win/samsung-galaxy-s8-mimic-iphone-7-remove-3-5mm-jack/">Samsung 
Galaxy S8 could mimic iPhone 7 and remove 3.5mm jack</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									One of the most 
controversial moments in technology this year was the elimination of the Apple 
iPhone 7 headset jack,…																							</DIV><!-- .dslc-blog-post-excerpt -->
																															 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/samsung-galaxy-s8-mimic-iphone-7-remove-3-5mm-jack/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->																					 
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/iphone-7-app-expel-water-speakers/"><IMG 
alt="" src="index_files/IPhone-7-has-an-app-to-expel-water-from-the-speakers-400x255.jpg"></A>
																							 </DIV><!-- .dslc-blog-post-thumb-inner -->											
										 </DIV><!-- .dslc-blog-post-thumb -->																									
									 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A href="http://freeiphone7plusgiveaway.win/iphone-7-app-expel-water-speakers/">IPhone 
7 has an app to expel water from the speakers</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									If you have water 
in the speakers of your iPhone 7, with the Sonic application you can fix it 
without…																							</DIV><!-- .dslc-blog-post-excerpt -->										
																					 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/iphone-7-app-expel-water-speakers/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->																					 
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-last-col dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/instagram-updated-upgrade-iphone-7-iphone-7-plus/"><IMG 
alt="" src="index_files/Instagram-is-updated-with-upgrade-for-iPhone-7-and-iPhone-7-Plus-400x193.jpg"></A>
																							 </DIV><!-- .dslc-blog-post-thumb-inner -->											
										 </DIV><!-- .dslc-blog-post-thumb -->																									
									 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A href="http://freeiphone7plusgiveaway.win/instagram-updated-upgrade-iphone-7-iphone-7-plus/">Instagram 
is updated with upgrade for iPhone 7 and iPhone 7 Plus</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									It seems that 
Instagram has made some updates from the server that add support for capturing a 
wide range of…																							</DIV><!-- .dslc-blog-post-excerpt -->
																															 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/instagram-updated-upgrade-iphone-7-iphone-7-plus/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->																					 
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-first-col dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/how-to-win-a-free-iphone-7-plus/"><IMG 
alt="" src="index_files/Win-a-Free-iPhone-7-Plus-400x225.jpg"></A>
																							 </DIV><!-- .dslc-blog-post-thumb-inner -->											
										 </DIV><!-- .dslc-blog-post-thumb -->																									
									 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A href="http://freeiphone7plusgiveaway.win/how-to-win-a-free-iphone-7-plus/">How 
to Win a Free iPhone 7 Plus</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									Do you want to have 
in your pocket iPhone 7 plus? Certainly not hesitate and try your luck in 
this…																							</DIV><!-- .dslc-blog-post-excerpt -->										
																					 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/how-to-win-a-free-iphone-7-plus/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->																					 
<DIV class="dslc-post dslc-blog-post dslc-masonry-item dslc-col dslc-4-col  dslc-post-format-standard" 
data-cats="news ">
<DIV class="dslc-blog-post-thumb dslc-post-thumb dslc-on-hover-anim">
<DIV class="dslc-blog-post-thumb-inner dslca-post-thumb"><A href="http://freeiphone7plusgiveaway.win/potential-shortage-parts-new-iphone/"><IMG 
alt="" 
src="index_files/Potential-shortage-of-parts-for-new-iPhone-400x225.png"></A>
																							 </DIV><!-- .dslc-blog-post-thumb-inner -->											
										 </DIV><!-- .dslc-blog-post-thumb -->																									
									 
<DIV class="dslc-post-main dslc-blog-post-main">
<DIV class="dslc-blog-post-title">
<H2><A href="http://freeiphone7plusgiveaway.win/potential-shortage-parts-new-iphone/">Potential 
shortage of parts for new iPhone</A></H2></DIV><!-- .dslc-blog-post-title -->
																																									 
<DIV class="dslc-blog-post-excerpt">																									There is a chance 
that with the launch of Apple's new smartphone, there are a limited number of 
aircraft will…																							</DIV><!-- .dslc-blog-post-excerpt -->
																															 
<DIV class="dslc-blog-post-read-more"><A href="http://freeiphone7plusgiveaway.win/potential-shortage-parts-new-iphone/">CONTINUE 
READING												</A>											 </DIV><!-- .dslc-blog-post-read-more -->
																			 </DIV><!-- .blog-post-main -->																	
							 </DIV><!-- .dslc-blog-post -->														 </DIV><!-- .dslc-posts-inner --></DIV><!-- .dslc-blog-posts -->
				 </DIV><!-- .dslc-module -->		 </DIV></DIV></DIV>
<DIV class="dslc-modules-section " style='background-position: center; padding-top: 121px; padding-bottom: 121px; background-image: url("http://freeiphone7plusgiveaway.win/wp-content/uploads/2015/10/cityscape-918831_1280.jpg"); background-repeat: no-repeat; background-size: cover; background-color: rgba(0, 0, 0, 0);'>
<DIV class="dslc-bg-video dslc-force-show">
<DIV class="dslc-bg-video-overlay" style="opacity: 0.9; background-color: rgb(239, 241, 248);"></DIV></DIV>
<DIV class="dslc-modules-section-wrapper dslc-clearfix">
<DIV class="dslc-modules-area dslc-col dslc-12-col dslc-last-col" 
data-size="12">
<DIV class="dslc-module-front dslc-module-DSLC_Text_Simple dslc-in-viewport-check dslc-in-viewport-anim-none  dslc-col dslc-12-col dslc-last-col  dslc-module-handle-like-regular " 
id="dslc-module-4ffa8e6a976" data-dslc-preset="none" data-dslc-anim-easing="ease" 
data-dslc-anim-duration="650" data-dslc-anim-delay="0" data-dslc-anim="none" 
data-dslc-module-size="12" data-dslc-module-id="DSLC_Text_Simple" 
data-module-id="4ffa8e6a976">
<DIV class="dslc-text-module-content">
<H3 style="text-align: center;"><SPAN class="st" 
style="color: rgb(0, 0, 0);">Everyone is very possible to get a free iPhone 7 
Plus, Take a Chance and Win Free iPhone 7 Now !!</SPAN></H3></DIV></DIV><!-- .dslc-module -->
				 
<DIV class="dslc-module-front dslc-module-DSLC_Button dslc-in-viewport-check dslc-in-viewport-anim-none  dslc-col dslc-12-col dslc-last-col  dslc-module-handle-like-regular " 
id="dslc-module-247" data-dslc-preset="none" data-dslc-anim-easing="ease" 
data-dslc-anim-duration="650" data-dslc-anim-delay="0" data-dslc-anim="none" 
data-dslc-module-size="12" data-dslc-module-id="DSLC_Button" data-module-id="247">
<DIV class="dslc-button"><A onclick="" href="http://freeiphone7plusgiveaway.win/win/" 
target="_blank" rel="nofollow">																			Win iPhone 7 
Now!!																	</A>							 </DIV><!-- .dslc-button -->										 </DIV><!-- .dslc-module -->
				 
<DIV class="dslc-module-front dslc-module-DSLC_Text_Simple dslc-in-viewport-check dslc-in-viewport-anim-none  dslc-col dslc-12-col dslc-last-col  dslc-module-handle-like-regular " 
id="dslc-module-b39e0d5f818" data-dslc-preset="none" data-dslc-anim-easing="ease" 
data-dslc-anim-duration="650" data-dslc-anim-delay="0" data-dslc-anim="none" 
data-dslc-module-size="12" data-dslc-module-id="DSLC_Text_Simple" 
data-module-id="b39e0d5f818">
<DIV class="dslc-text-module-content">
<H4 style="text-align: center;"></H4>
<H4 style="text-align: center;"><SPAN style="color: rgb(0, 0, 255);"><A style="color: rgb(0, 0, 255);" 
href="http://www.apple.com/iphone-7/" target="_blank"><STRONG>Go to the official 
website apple.com</STRONG></A></SPAN></H4>
<H3 style="text-align: center;">Disclaimer</H3>
<P style="text-align: center;"><SPAN style="color: rgb(0, 0, 0);"><EM>This site 
is not owned or operated by, is not accredited by nor is a subsidiary of Apple 
Inc. iPhone is a brand of Apple Inc. The content of this amazing site is not 
reviewed or supplied by Apple Inc. All articles, images, logos and trademarks in 
this web site are property of the respective owners. Please follow this connect 
to browse the complete disclaimer.</EM></SPAN></P></DIV></DIV><!-- .dslc-module -->
		 </DIV></DIV></DIV></DIV></DIV></main>
                    <!-- #main -->
                </div>
                <!-- #primary -->
            </div>
        </div>
        <!-- #content -->
        <a class="go-top"><i class="fa fa-angle-up"></i></a>
        <footer class="site-footer" id="colophon" role="contentinfo">
<DIV class="site-info container">			Copyright ©  2016 - 2017 <A href="file:///C:/">Free 
iPhone7 Plus Giveaway</A>			 <SPAN class="sep"> | </SPAN>			Theme: <A href="http://athemes.com/theme/west" 
rel="designer">West</A> by aThemes.		</DIV><!-- .site-info -->	 </footer>
        <!-- #colophon -->
    </div>
    <!-- #page -->
    <script type="text/javascript">
/* <![CDATA[ */
var mejsL10n = {"language":"en-US","strings":{"Close":"Close","Fullscreen":"Fullscreen","Turn off Fullscreen":"Turn off Fullscreen","Go Fullscreen":"Go Fullscreen","Download File":"Download File","Download Video":"Download Video","Play":"Play","Pause":"Pause","Captions\/Subtitles":"Captions\/Subtitles","None":"None","Time Slider":"Time Slider","Skip back %1 seconds":"Skip back %1 seconds","Video Player":"Video Player","Audio Player":"Audio Player","Volume Slider":"Volume Slider","Mute Toggle":"Mute Toggle","Unmute":"Unmute","Mute":"Mute","Use Up\/Down Arrow keys to increase or decrease volume.":"Use Up\/Down Arrow keys to increase or decrease volume.","Use Left\/Right Arrow keys to advance one second, Up\/Down arrows to advance ten seconds.":"Use Left\/Right Arrow keys to advance one second, Up\/Down arrows to advance ten seconds."}};
var _wpmejsSettings = {"pluginPath":"\/wp-includes\/js\/mediaelement\/"};
/* ]]> */
</script>
    <script src="index_files/mediaelement-and-player.min.js" type="text/javascript"></script>
    <script src="index_files/wp-mediaelement.min.js" type="text/javascript"></script>
    <script src="index_files/imagesloaded.min.js" type="text/javascript"></script>
    <script src="index_files/masonry.min.js" type="text/javascript"></script>
    <script src="index_files/jquery.masonry.min.js" type="text/javascript"></script>
    <script type="text/javascript">
/* <![CDATA[ */
var DSLCAjax = {"ajaxurl":"http:\/\/freeiphone7plusgiveaway.win\/wp-admin\/admin-ajax.php"};
/* ]]> */
</script>
    <script src="index_files/main.js" type="text/javascript"></script>
    <script type="text/javascript">
/* <![CDATA[ */
var mashsb = {"shares":"632","round_shares":"1","animate_shares":"1","dynamic_buttons":"0","share_url":"http:\/\/freeiphone7plusgiveaway.win\/","title":"Home","image":null,"desc":"","hashtag":"","subscribe":"content","subscribe_url":"","activestatus":"1","singular":"1","twitter_popup":"1","refresh":"0"};
/* ]]> */
</script>
    <script src="index_files/mashsb.min.js" type="text/javascript"></script>
    <script src="index_files/skip-link-focus-fix.js" type="text/javascript"></script>
    <script src="index_files/main(1).js" type="text/javascript"></script>
    <script src="index_files/scripts.min.js" type="text/javascript"></script>
    <script src="index_files/wp-embed.min.js" type="text/javascript"></script>
</body>
</html>
